[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "dbmate"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci"]

[deploy]
startCommand = "dbmate up && npx next start"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
