require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

# Required for FirebaseCoreInternal (Swift pod) to import GoogleUtilities as a static library
pod 'GoogleUtilities', :modular_headers => true

prepare_react_native_project!

target 'SQUADD' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    # Xcode 26: disable explicit modules (causes cascading "unable to resolve module dependency")
    installer.pods_project.build_configurations.each do |bc|
      bc.build_settings['CLANG_ENABLE_EXPLICIT_MODULES'] = 'NO'
      bc.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |bc|
        bc.build_settings['CLANG_ENABLE_EXPLICIT_MODULES'] = 'NO'
        bc.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
        if target.name == 'hermes-engine'
          bc.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
          bc.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO'
        end
      end
    end

    # Fix with-environment.sh unquoted $1 (breaks on paths with spaces)
    with_env = File.join(config[:reactNativePath], 'scripts', 'xcode', 'with-environment.sh')
    if File.exist?(with_env)
      env_content = File.read(with_env)
      if env_content.include?("  $1\n") && !env_content.include?("  \"$1\"\n")
        env_content.gsub!("  $1\n", "  \"$1\"\n")
        File.write(with_env, env_content)
      end
    end

    # Fix Hermes replace_hermes_version.js unquoted tar paths
    hermes_js = File.join(config[:reactNativePath], 'sdks', 'hermes-engine', 'utils', 'replace_hermes_version.js')
    if File.exist?(hermes_js)
      hermes_content = File.read(hermes_js)
      if hermes_content.include?('tar -xf ${tarballURLPath} -C ${finalLocation}')
        hermes_content.gsub!('tar -xf ${tarballURLPath} -C ${finalLocation}',
                             'tar -xf "${tarballURLPath}" -C "${finalLocation}"')
        File.write(hermes_js, hermes_content)
      end
    end
  end
end

# Fix space-in-path: runs AFTER CocoaPods writes project.pbxproj to disk
post_integrate do |installer|
  patch_script = File.join(__dir__, '..', 'scripts', 'patch-pods-space.sh')
  system("sh", patch_script) if File.exist?(patch_script)
end
