"use client";

import {
  useState,
  useRef,
  useEffect,
  useCallback,
  type KeyboardEvent,
} from "react";

// ─── Profile ──────────────────────────────────────────────────────────────────

type PicklePeteProfile = Record<string, string | number | boolean>;

const PROFILE_KEY = "pickle_pete_profile";

function loadProfile(): PicklePeteProfile | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(PROFILE_KEY);
    return raw ? (JSON.parse(raw) as PicklePeteProfile) : null;
  } catch {
    return null;
  }
}

function mergeAndSaveProfile(updates: Record<string, unknown>): PicklePeteProfile {
  const existing = loadProfile() ?? {};
  const merged: PicklePeteProfile = {
    ...existing,
    ...(updates as PicklePeteProfile),
    updatedAt: Date.now(),
  };
  try {
    localStorage.setItem(PROFILE_KEY, JSON.stringify(merged));
  } catch { /* quota — ignore */ }
  return merged;
}

function forgetProfile(): void {
  try {
    localStorage.removeItem(PROFILE_KEY);
  } catch { /* ignore */ }
}

function detectLanguage(text: string): "vi" | "en" {
  const vi = /[àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]/i;
  return vi.test(text) ? "vi" : "en";
}

function buildProfileSummary(profile: PicklePeteProfile): string {
  const parts: string[] = [];
  if (profile.dupr) parts.push(`${profile.dupr} DUPR`);
  if (profile.district) parts.push(String(profile.district));
  if (profile.play_time) parts.push(`${profile.play_time} player`);
  if (profile.play_style) parts.push(String(profile.play_style));
  return parts.slice(0, 4).join(" · ");
}

// ─── i18n strings ─────────────────────────────────────────────────────────────

const UI = {
  en: {
    title: "Find your game — Experimental",
    subtitle: "Ask me anything",
    placeholder: "Ask anything about pickleball in HCM…",
    footer: "Data from Reclub.co · Updated hourly",
    closeLabel: "Close",
    sendLabel: "Send",
    emptyPrompt: "Ask about venues, upcoming sessions, or clubs in Ho Chi Minh City.",
    suggestions: [
      "When can I play today?",
      "Best clubs for 3.0 players?",
      "Sessions near District 1 tonight?",
      "Which sessions still have spots?",
    ],
    errors: {
      403: "AI assistant is not available right now.",
      429: "You've sent too many messages. Please wait a few minutes.",
      500: "Something went wrong. Please try again.",
    } as Record<number, string>,
    popupTitle: "🧪 Experimental feature",
    popupBody:
      "Pickle Pete is an AI assistant that knows every court and session in HCM. Responses are generated by AI and may not always be perfect — always verify on Reclub before booking.",
    popupCta: "Got it, let's play!",
    charRemaining: (n: number) => `${n} remaining`,
    forget: "forget",
    yourProfile: "Your profile",
    profileModalTitle: "Your profile",
    profileModalEmpty: "No profile saved yet. Chat a bit and I'll remember your preferences!",
    profileModalClose: "Close",
    forgetField: "forget",
    forgetAll: "Forget all",
  },
  vi: {
    title: "Tìm buổi chơi — Thử nghiệm",
    subtitle: "Hỏi bất cứ điều gì",
    placeholder: "Hỏi về sân, buổi chơi, câu lạc bộ ở HCM…",
    footer: "Dữ liệu từ Reclub.co · Cập nhật mỗi giờ",
    closeLabel: "Đóng",
    sendLabel: "Gửi",
    emptyPrompt: "Hỏi về sân, buổi chơi hoặc câu lạc bộ ở Thành phố Hồ Chí Minh.",
    suggestions: [
      "Hôm nay có buổi chơi nào không?",
      "CLB tốt cho người chơi 3.0?",
      "Buổi tối nay gần Quận 1?",
      "Buổi nào còn chỗ trống?",
    ],
    errors: {
      403: "Trợ lý AI hiện không khả dụng.",
      429: "Bạn đã gửi quá nhiều tin nhắn. Vui lòng thử lại sau.",
      500: "Có lỗi xảy ra. Vui lòng thử lại.",
    } as Record<number, string>,
    popupTitle: "🧪 Tính năng thử nghiệm",
    popupBody:
      "Pickle Pete là trợ lý AI biết mọi sân và buổi chơi ở HCM. Câu trả lời được tạo bởi AI và có thể chưa hoàn toàn chính xác — hãy kiểm tra lại trên Reclub trước khi đặt.",
    popupCta: "Hiểu rồi, chơi thôi!",
    charRemaining: (n: number) => `còn ${n} ký tự`,
    forget: "quên",
    yourProfile: "Hồ sơ của bạn",
    profileModalTitle: "Hồ sơ của bạn",
    profileModalEmpty: "Chưa có thông tin. Hãy trò chuyện thêm để tôi ghi nhớ sở thích của bạn!",
    profileModalClose: "Đóng",
    forgetField: "xoá",
    forgetAll: "Xoá tất cả",
  },
};

// ─── Typing indicator ─────────────────────────────────────────────────────────

function TypingDots() {
  return (
    <div className="flex gap-1 items-center px-4 py-3">
      <span className="w-1.5 h-1.5 rounded-full bg-gray-400 animate-bounce [animation-delay:-0.3s]" />
      <span className="w-1.5 h-1.5 rounded-full bg-gray-400 animate-bounce [animation-delay:-0.15s]" />
      <span className="w-1.5 h-1.5 rounded-full bg-gray-400 animate-bounce" />
    </div>
  );
}

// ─── Experimental disclaimer popup ───────────────────────────────────────────

function ExperimentalPopup({
  locale,
  onConfirm,
}: {
  locale: "en" | "vi";
  onConfirm: () => void;
}) {
  const s = UI[locale];
  return (
    <div className="absolute inset-0 z-10 flex items-center justify-center bg-gray-950/90 backdrop-blur-sm rounded-t-2xl sm:rounded-2xl px-6">
      <div className="bg-gray-900 border border-gray-700 rounded-2xl p-6 max-w-xs w-full shadow-2xl text-center space-y-4">
        <p className="text-base font-semibold text-white">{s.popupTitle}</p>
        <p className="text-sm text-gray-400 leading-relaxed">{s.popupBody}</p>
        <button
          onClick={onConfirm}
          className="w-full bg-emerald-600 hover:bg-emerald-500 active:bg-emerald-700 text-white font-medium text-sm py-2.5 rounded-xl transition"
        >
          {s.popupCta}
        </button>
      </div>
    </div>
  );
}

// ─── Profile field label prettifier ──────────────────────────────────────────

function prettyKey(key: string): string {
  return key
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function prettyValue(value: string | number | boolean): string {
  if (typeof value === "boolean") return value ? "Yes" : "No";
  return String(value);
}

// ─── Profile modal ────────────────────────────────────────────────────────────

function ProfileModal({
  locale,
  profile,
  onForgetField,
  onForgetAll,
  onClose,
}: {
  locale: "en" | "vi";
  profile: PicklePeteProfile;
  onForgetField: (key: string) => void;
  onForgetAll: () => void;
  onClose: () => void;
}) {
  const s = UI[locale];
  const fields = Object.entries(profile).filter(([k]) => k !== "updatedAt");

  return (
    <div
      className="fixed inset-0 z-[60] flex items-end justify-center sm:items-center bg-black/60 backdrop-blur-sm"
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        className="w-full sm:w-[400px] bg-gray-900 border border-gray-700 rounded-t-2xl sm:rounded-2xl shadow-2xl flex flex-col overflow-hidden max-h-[70vh]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 pt-5 pb-3 border-b border-gray-800">
          <p className="text-sm font-semibold text-white">{s.profileModalTitle}</p>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-300 transition p-1 rounded-lg hover:bg-gray-800"
          >
            <svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor">
              <path d="M3.72 3.72a.75.75 0 0 1 1.06 0L8 6.94l3.22-3.22a.75.75 0 1 1 1.06 1.06L9.06 8l3.22 3.22a.75.75 0 1 1-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 0 1-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 0 1 0-1.06Z" />
            </svg>
          </button>
        </div>

        {/* Field list */}
        <div className="flex-1 overflow-y-auto px-5 py-4 space-y-1">
          {fields.length === 0 ? (
            <p className="text-xs text-gray-500 leading-relaxed text-center py-4">
              {s.profileModalEmpty}
            </p>
          ) : (
            fields.map(([key, value]) => (
              <div
                key={key}
                className="flex items-center justify-between py-2 border-b border-gray-800/60 last:border-0"
              >
                <div className="min-w-0">
                  <p className="text-[11px] text-gray-500 uppercase tracking-wide">{prettyKey(key)}</p>
                  <p className="text-sm text-gray-200 truncate">{prettyValue(value as string | number | boolean)}</p>
                </div>
                <button
                  onClick={() => onForgetField(key)}
                  className="ml-4 text-[11px] text-gray-600 hover:text-red-400 transition underline underline-offset-2 shrink-0"
                >
                  {s.forgetField}
                </button>
              </div>
            ))
          )}
        </div>

        {/* Footer actions */}
        {fields.length > 0 && (
          <div className="px-5 pb-5 pt-3 border-t border-gray-800 flex justify-end">
            <button
              onClick={onForgetAll}
              className="text-xs text-red-500 hover:text-red-400 transition underline underline-offset-2"
            >
              {s.forgetAll}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Main modal ───────────────────────────────────────────────────────────────

interface Message {
  role: "user" | "assistant";
  content: string;
  suggestions?: string[];
}

interface AiChatModalProps {
  isOpen: boolean;
  onClose: () => void;
  sessionId: string;
  messages: Message[];
  onMessagesChange: (msgs: Message[]) => void;
  locale?: "en" | "vi";
  disclaimerSeen: boolean;
  onDisclaimerSeen: () => void;
}

export function AiChatModal({
  isOpen,
  onClose,
  sessionId,
  messages,
  onMessagesChange,
  locale = "vi",
  disclaimerSeen,
  onDisclaimerSeen,
}: AiChatModalProps) {
  const s = UI[locale];

  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [modalHeight, setModalHeight] = useState<number | null>(null);
  const [profile, setProfile] = useState<PicklePeteProfile | null>(null);
  const [profileModalOpen, setProfileModalOpen] = useState(false);

  const bottomRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const chatAreaRef = useRef<HTMLDivElement>(null);

  const hasSentFirstMessage = messages.some((m) => m.role === "user");

  // Load profile from localStorage on mount
  useEffect(() => {
    setProfile(loadProfile());
  }, []);

  // Auto-scroll to bottom on new messages
  useEffect(() => {
    if (isOpen) {
      requestAnimationFrame(() => {
        bottomRef.current?.scrollIntoView({ behavior: "smooth" });
      });
    }
  }, [messages, isLoading, isOpen]);

  // Focus input when popup is dismissed or modal opens without popup
  useEffect(() => {
    if (isOpen && disclaimerSeen) {
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  }, [isOpen, disclaimerSeen]);

  // Mobile keyboard handling — shrink modal when keyboard appears
  useEffect(() => {
    if (!isOpen || typeof window === "undefined" || !window.visualViewport) return;
    const vv = window.visualViewport;
    function handleResize() {
      if (!vv) return;
      const keyboardHeight = window.innerHeight - vv.height;
      if (keyboardHeight > 100) {
        setModalHeight(vv.height - 16);
      } else {
        setModalHeight(null);
      }
    }
    vv.addEventListener("resize", handleResize);
    return () => vv.removeEventListener("resize", handleResize);
  }, [isOpen]);

  const sendMessage = useCallback(
    async (text: string) => {
      const trimmed = text.trim();
      if (!trimmed || isLoading) return;

      // Detect and save language on first message
      const currentProfile = loadProfile();
      if (!currentProfile?.language) {
        const lang = detectLanguage(trimmed);
        const updated = mergeAndSaveProfile({ language: lang });
        setProfile(updated);
      }

      const userMsg: Message = { role: "user", content: trimmed };
      const nextMessages = [...messages, userMsg];
      onMessagesChange(nextMessages);
      setInput("");
      setError(null);
      setIsLoading(true);

      if (inputRef.current) {
        inputRef.current.style.height = "auto";
      }

      try {
        const latestProfile = loadProfile();
        const res = await fetch("/api/heatmap/ai-chat", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            messages: nextMessages.map((m) => ({ role: m.role, content: m.content })),
            sessionId,
            profile: latestProfile ?? undefined,
          }),
        });

        const data = await res.json() as {
          content?: string;
          error?: string;
          profileUpdate?: Record<string, unknown>;
          suggestions?: string[];
        };

        if (!res.ok) {
          setError(s.errors[res.status] ?? s.errors[500]);
          onMessagesChange(messages);
          return;
        }

        // Merge profile update returned by the AI
        if (data.profileUpdate && Object.keys(data.profileUpdate).length > 0) {
          const updated = mergeAndSaveProfile(data.profileUpdate);
          setProfile(updated);
        }

        onMessagesChange([
          ...nextMessages,
          {
            role: "assistant",
            content: data.content ?? "",
            suggestions: data.suggestions?.length ? data.suggestions : undefined,
          },
        ]);
      } catch {
        setError(s.errors[500]);
        onMessagesChange(messages);
      } finally {
        setIsLoading(false);
      }
    },
    [isLoading, messages, onMessagesChange, sessionId, s],
  );

  const handleKeyDown = useCallback(
    (e: KeyboardEvent<HTMLTextAreaElement>) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        sendMessage(input);
      }
    },
    [input, sendMessage],
  );

  const handleBackdropClick = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      if (e.target === e.currentTarget) onClose();
    },
    [onClose],
  );

  const handleDisclaimerConfirm = useCallback(() => {
    onDisclaimerSeen();
    setTimeout(() => inputRef.current?.focus(), 100);
  }, [onDisclaimerSeen]);

  const handleForgetProfile = useCallback(() => {
    forgetProfile();
    setProfile(null);
    setProfileModalOpen(false);
  }, []);

  const handleForgetField = useCallback((key: string) => {
    const current = loadProfile();
    if (!current) return;
    const { [key]: _removed, ...rest } = current;
    try {
      localStorage.setItem(PROFILE_KEY, JSON.stringify({ ...rest, updatedAt: Date.now() }));
    } catch { /* ignore */ }
    const updated = loadProfile();
    setProfile(updated);
    if (updated && Object.keys(updated).filter((k) => k !== "updatedAt").length === 0) {
      setProfileModalOpen(false);
    }
  }, []);

  const handleSuggestionTap = useCallback(
    (suggestion: string) => {
      // Clear pills on the last assistant message so they don't linger
      const cleared = messages.map((m, i) =>
        i === messages.length - 1 ? { ...m, suggestions: [] as string[] } : m,
      );
      onMessagesChange(cleared);
      sendMessage(suggestion);
    },
    [messages, onMessagesChange, sendMessage],
  );

  if (!isOpen) return null;

  const profileSummary = profile ? buildProfileSummary(profile) : "";

  return (
    /* Backdrop */
    <div
      className="fixed inset-0 z-50 flex items-end justify-center sm:items-center bg-black/50 backdrop-blur-sm"
      onClick={handleBackdropClick}
    >
      {/* Modal panel */}
      <div
        className="relative w-full sm:w-[480px] bg-gray-950 border border-gray-800 rounded-t-2xl sm:rounded-2xl shadow-2xl flex flex-col overflow-hidden"
        style={{
          maxHeight: modalHeight ? `${modalHeight}px` : "min(90vh, 680px)",
          height: modalHeight ? `${modalHeight}px` : undefined,
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Experimental disclaimer overlay */}
        {!disclaimerSeen && (
          <ExperimentalPopup locale={locale} onConfirm={handleDisclaimerConfirm} />
        )}

        {/* Header */}
        <div className="shrink-0 px-5 pt-5 pb-3 border-b border-gray-800">
          {/* Drag handle on mobile */}
          <div className="absolute left-1/2 -translate-x-1/2 top-2.5 w-10 h-1 rounded-full bg-gray-700 sm:hidden" />

          <div className="flex items-start justify-between">
            <div className="mt-1 min-w-0 flex-1 pr-3">
              <div className="flex items-center gap-2">
                <span className="text-base">🏓</span>
                <h2 className="text-sm font-semibold text-white">{s.title}</h2>
              </div>
              <p className="text-[11px] text-gray-500 mt-0.5">{s.subtitle}</p>
            </div>

            <button
              onClick={onClose}
              className="text-gray-500 hover:text-gray-300 transition p-1 -mr-1 mt-0.5 rounded-lg hover:bg-gray-800 shrink-0"
              aria-label={s.closeLabel}
            >
              <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                <path d="M3.72 3.72a.75.75 0 0 1 1.06 0L8 6.94l3.22-3.22a.75.75 0 1 1 1.06 1.06L9.06 8l3.22 3.22a.75.75 0 1 1-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 0 1-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 0 1 0-1.06Z" />
              </svg>
            </button>
          </div>

          {/* "Your profile" link — only when profile has data */}
          {profileSummary && (
            <div className="flex justify-end mt-1">
              <button
                onClick={() => setProfileModalOpen(true)}
                className="text-[10px] text-gray-500 hover:text-emerald-400 transition underline underline-offset-2"
              >
                {s.yourProfile}
              </button>
            </div>
          )}
        </div>

        {/* Chat area */}
        <div
          ref={chatAreaRef}
          className="flex-1 overflow-y-auto px-4 py-4 space-y-3 overscroll-contain"
        >
          {/* Empty state with suggestions */}
          {messages.length === 0 && !hasSentFirstMessage && (
            <div className="flex flex-col items-center justify-center h-full gap-4 py-6">
              <p className="text-xs text-gray-500 text-center max-w-xs leading-relaxed">
                {s.emptyPrompt}
              </p>
              <div className="flex flex-wrap gap-2 justify-center">
                {s.suggestions.map((suggestion) => (
                  <button
                    key={suggestion}
                    onClick={() => sendMessage(suggestion)}
                    disabled={isLoading}
                    className="text-xs bg-gray-800 hover:bg-gray-700 border border-gray-700 hover:border-gray-600 text-gray-300 hover:text-white rounded-full px-3 py-1.5 transition"
                  >
                    {suggestion}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Message bubbles */}
          {messages.map((msg, i) => (
            <div
              key={i}
              className={`flex flex-col ${msg.role === "user" ? "items-end" : "items-start"}`}
            >
              <div
                className={`rounded-2xl px-4 py-2.5 text-sm leading-relaxed whitespace-pre-wrap ${
                  msg.role === "user"
                    ? "max-w-[82%] bg-emerald-600 text-white rounded-br-sm"
                    : "w-[90%] bg-gray-800/80 text-gray-100 rounded-bl-sm"
                }`}
              >
                {msg.content}
              </div>

              {/* Suggestion pills — only on assistant messages, only when present */}
              {msg.role === "assistant" && msg.suggestions && msg.suggestions.length > 0 && (
                <div className="flex flex-wrap gap-2 mt-2 pl-1">
                  {msg.suggestions.map((sug) => (
                    <button
                      key={sug}
                      onClick={() => handleSuggestionTap(sug)}
                      disabled={isLoading}
                      className="text-xs px-3.5 py-1.5 rounded-full border border-white/20 bg-white/8 text-white hover:bg-white/15 active:bg-white/20 transition disabled:opacity-40 whitespace-nowrap"
                    >
                      {sug}
                    </button>
                  ))}
                </div>
              )}
            </div>
          ))}

          {/* Typing indicator */}
          {isLoading && (
            <div className="flex justify-start">
              <div className="bg-gray-800/80 rounded-2xl rounded-bl-sm">
                <TypingDots />
              </div>
            </div>
          )}

          {/* Error state */}
          {error && (
            <div className="flex justify-center">
              <p className="text-xs text-red-400 text-center max-w-xs px-2">{error}</p>
            </div>
          )}

          <div ref={bottomRef} />
        </div>

        {/* Input area */}
        <div className="shrink-0 px-4 pb-4 pt-2 border-t border-gray-800 bg-gray-950">
          <div className="flex gap-2 items-end">
            <textarea
              ref={inputRef}
              value={input}
              onChange={(e) => {
                if (e.target.value.length <= 200) setInput(e.target.value);
                e.target.style.height = "auto";
                e.target.style.height = `${Math.min(e.target.scrollHeight, 96)}px`;
              }}
              onKeyDown={handleKeyDown}
              placeholder={s.placeholder}
              rows={1}
              maxLength={200}
              disabled={isLoading}
              className="flex-1 bg-gray-800 border border-gray-700 rounded-xl px-3.5 py-2.5 text-sm text-white placeholder-gray-500 resize-none focus:outline-none focus:border-emerald-600 transition leading-relaxed"
              style={{ minHeight: "40px", maxHeight: "96px" }}
            />
            <button
              onClick={() => sendMessage(input)}
              disabled={isLoading || !input.trim()}
              className="shrink-0 bg-emerald-600 hover:bg-emerald-500 disabled:bg-gray-700 disabled:text-gray-500 text-white rounded-xl px-4 py-2.5 text-sm font-medium transition h-10 flex items-center"
              aria-label={s.sendLabel}
            >
              <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                <path d="M.5 1.163A1 1 0 0 1 1.97.28l12.868 6.837a1 1 0 0 1 0 1.766L1.969 15.72A1 1 0 0 1 .5 14.836V10.33a1 1 0 0 1 .816-.983L8.5 8 1.316 6.653A1 1 0 0 1 .5 5.67V1.163Z" />
              </svg>
            </button>
          </div>
          {input.length > 160 && (
            <p className="text-[10px] text-gray-600 mt-1 text-right">
              {s.charRemaining(200 - input.length)}
            </p>
          )}
        </div>

        {/* Footer */}
        <div className="shrink-0 px-5 pb-4 pt-0">
          <p className="text-[10px] text-gray-700 text-center">{s.footer}</p>
        </div>
      </div>

      {/* Profile modal — rendered outside the main panel so it overlays correctly */}
      {profileModalOpen && profile && (
        <ProfileModal
          locale={locale}
          profile={profile}
          onForgetField={handleForgetField}
          onForgetAll={handleForgetProfile}
          onClose={() => setProfileModalOpen(false)}
        />
      )}
    </div>
  );
}
